
// Demo data for static/demo use only
export const demoCourses = [
  {
    id: 1,
    title: "JavaScript Basics",
    description: "Learn the fundamentals of JavaScript, the most popular programming language. Master variables, functions, arrays, objects, and more.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    instructor: "John Smith",
    points: 0,
    tags: ["Beginner", "Frontend"],
    duration: "12 hours",
    rating: "4.9",
    lessons: [
      { id: 1, title: "Introduction to JavaScript", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Variables and Data Types", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "Operators and Expressions", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "Control Structures (If/Else)", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Loops and Iteration", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Functions and Scope", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Objects and Arrays", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "DOM Manipulation", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Events and Event Listeners", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Asynchronous JavaScript", videoId: "dQw4w9WgXcQ" },
      { id: 11, title: "ES6 Features and Modern Syntax", videoId: "dQw4w9WgXcQ" },
      { id: 12, title: "Debugging and Best Practices", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 2,
    title: "React Fundamentals",
    description: "Master the basics of React and build modern, interactive web applications. Learn components, hooks, and state management.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original.svg",
    instructor: "Sarah Johnson",
    points: 100,
    tags: ["Intermediate", "Frontend"],
    duration: "16 hours",
    rating: "4.8",
    lessons: [
      { id: 1, title: "Introduction to React", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Components and JSX", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "Props and Component Communication", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "State and useState Hook", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "useEffect and Side Effects", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Handling Events", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Conditional Rendering", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "Lists and Keys", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Forms and Controlled Components", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Context API and useContext", videoId: "dQw4w9WgXcQ" },
      { id: 11, title: "Custom Hooks", videoId: "dQw4w9WgXcQ" },
      { id: 12, title: "Performance Optimization", videoId: "dQw4w9WgXcQ" },
      { id: 13, title: "Testing React Components", videoId: "dQw4w9WgXcQ" },
      { id: 14, title: "Building a Real Project", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 3,
    title: "TypeScript for Professionals",
    description: "Learn TypeScript to build more robust and scalable applications. Master types, interfaces, generics, and advanced patterns.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/typescript/typescript-original.svg",
    instructor: "Michael Chen",
    points: 150,
    tags: ["Intermediate", "Backend"],
    duration: "14 hours",
    rating: "4.7",
    lessons: [
      { id: 1, title: "Introduction to TypeScript", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Basic Types", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "Interfaces and Type Aliases", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "Classes and Inheritance", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Generics", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Enums and Constants", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Decorators and Metadata", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "Advanced Types", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Modules and Namespaces", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Type Guards and Narrowing", videoId: "dQw4w9WgXcQ" },
      { id: 11, title: "Working with External Libraries", videoId: "dQw4w9WgXcQ" },
      { id: 12, title: "Configuration and Tooling", videoId: "dQw4w9WgXcQ" },
      { id: 13, title: "Best Practices and Patterns", videoId: "dQw4w9WgXcQ" },
      { id: 14, title: "Real-world TypeScript Project", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 4,
    title: "Next.js Deep Dive",
    description: "Build full-stack web applications with Next.js. Learn about server-side rendering, API routes, and deployment strategies.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nextjs/nextjs-original.svg",
    instructor: "Emily Williams",
    points: 200,
    tags: ["Advanced", "Full-Stack"],
    duration: "18 hours",
    rating: "4.9",
    lessons: [
      { id: 1, title: "Getting Started with Next.js", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Pages and Routing", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "API Routes", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "Static Generation and SSG", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Server-Side Rendering (SSR)", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Incremental Static Regeneration", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Dynamic Routes", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "Image Optimization", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Font Optimization", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Data Fetching Patterns", videoId: "dQw4w9WgXcQ" },
      { id: 11, title: "Middleware and Authentication", videoId: "dQw4w9WgXcQ" },
      { id: 12, title: "Deployment and Production", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 5,
    title: "Python for Data Science",
    description: "Master Python programming for data science and machine learning. Learn NumPy, Pandas, and Scikit-Learn.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original.svg",
    instructor: "David Kumar",
    points: 100,
    tags: ["Intermediate", "Data Science"],
    duration: "20 hours",
    rating: "4.8",
    lessons: [
      { id: 1, title: "Python Basics and Setup", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Data Types and Structures", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "Functions and Modules", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "Working with NumPy", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Introduction to Pandas", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Data Cleaning and Preprocessing", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Data Visualization with Matplotlib", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "Statistical Analysis", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Introduction to Scikit-Learn", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Supervised Learning", videoId: "dQw4w9WgXcQ" },
      { id: 11, title: "Unsupervised Learning", videoId: "dQw4w9WgXcQ" },
      { id: 12, title: "Model Evaluation and Tuning", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 6,
    title: "Tailwind CSS Mastery",
    description: "Master Tailwind CSS for rapid UI development. Build responsive, modern designs with utility-first CSS.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/tailwindcss/tailwindcss-original.svg",
    instructor: "Lisa Anderson",
    points: 50,
    tags: ["Beginner", "Frontend"],
    duration: "10 hours",
    rating: "4.9",
    lessons: [
      { id: 1, title: "Introduction to Tailwind CSS", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Utility-First Approach", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "Responsive Design", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "Colors and Spacing", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Typography and Text Styling", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Flexbox and Grid", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Hover and Focus States", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "Animations and Transitions", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Customization and Configuration", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Building a Real Project", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 7,
    title: "Node.js Backend Development",
    description: "Build scalable backend applications with Node.js. Learn Express, databases, authentication, and APIs.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    instructor: "James Brown",
    points: 150,
    tags: ["Intermediate", "Backend"],
    duration: "16 hours",
    rating: "4.8",
    lessons: [
      { id: 1, title: "Introduction to Node.js", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "NPM and Package Management", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "Modules and File System", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "Introduction to Express", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Routing and Middleware", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Request and Response Handling", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Working with Databases", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "User Authentication", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Building RESTful APIs", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Error Handling and Validation", videoId: "dQw4w9WgXcQ" },
      { id: 11, title: "Deployment and Hosting", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 8,
    title: "MongoDB and Databases",
    description: "Learn MongoDB and database design principles. Master CRUD operations, indexing, and aggregation pipelines.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/mongodb/mongodb-original.svg",
    instructor: "Rachel Green",
    points: 100,
    tags: ["Intermediate", "Backend"],
    duration: "12 hours",
    rating: "4.7",
    lessons: [
      { id: 1, title: "Introduction to MongoDB", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Document Structure and BSON", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "CRUD Operations", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "Querying and Filtering", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Indexing and Performance", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Aggregation Pipeline", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Transactions and Atomicity", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "Schema Design Patterns", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Backup and Restore", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Mongoose ODM", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 9,
    title: "Vue.js Fundamentals",
    description: "Master Vue.js framework for building interactive user interfaces. Learn components, composition API, and state management.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vuejs/vuejs-original.svg",
    instructor: "Alex Martinez",
    points: 100,
    tags: ["Intermediate", "Frontend"],
    duration: "14 hours",
    rating: "4.8",
    lessons: [
      { id: 1, title: "Introduction to Vue.js", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Template Syntax", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "Reactive Data Binding", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "Components and Props", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Events and Forms", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "Conditional Rendering and Loops", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "Watchers and Computed Properties", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "Lifecycle Hooks", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Composition API", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "State Management with Pinia", videoId: "dQw4w9WgXcQ" },
      { id: 11, title: "Routing with Vue Router", videoId: "dQw4w9WgXcQ" },
    ],
  },
  {
    id: 10,
    title: "AWS Cloud Development",
    description: "Learn cloud development with AWS. Master EC2, S3, Lambda, and build scalable cloud applications.",
    image: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/amazonwebservices/amazonwebservices-original.svg",
    instructor: "Kevin Singh",
    points: 200,
    tags: ["Advanced", "Cloud"],
    duration: "22 hours",
    rating: "4.7",
    lessons: [
      { id: 1, title: "AWS Fundamentals", videoId: "dQw4w9WgXcQ" },
      { id: 2, title: "Setting Up AWS Account", videoId: "dQw4w9WgXcQ" },
      { id: 3, title: "EC2 Instances", videoId: "dQw4w9WgXcQ" },
      { id: 4, title: "S3 Storage", videoId: "dQw4w9WgXcQ" },
      { id: 5, title: "Lambda Functions", videoId: "dQw4w9WgXcQ" },
      { id: 6, title: "DynamoDB", videoId: "dQw4w9WgXcQ" },
      { id: 7, title: "RDS Databases", videoId: "dQw4w9WgXcQ" },
      { id: 8, title: "VPC and Networking", videoId: "dQw4w9WgXcQ" },
      { id: 9, title: "Security and IAM", videoId: "dQw4w9WgXcQ" },
      { id: 10, title: "Monitoring and Logging", videoId: "dQw4w9WgXcQ" },
    ],
  },
];

// Mongoose Course model for MongoDB (server-side only)
import mongoose from "mongoose";

const CourseSchema = new mongoose.Schema({
  title: { type: String, required: true },
  description: { type: String, required: true },
  image: { type: String },
  instructor: { type: String },
  points: { type: Number, default: 0 },
  tags: [String],
  duration: { type: String },
  rating: { type: Number || String },
  lessons: {
    type: mongoose.Schema.Types.Mixed,
    default: []
  },
  courseId: { type: String },
  id: { type: String },
  createdAt: { type: Date, default: Date.now }
});

const Course = mongoose.models.Course || mongoose.model("Course", CourseSchema);
export default Course;
